info:
  app:
    name: Eureka Server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/


spring:
  application:
    name: eureka
  redis:
    host: localhost
    port: 6379
#  session:
#    store-type: redis