server.port: 8089
spring:
  profiles:
    #active: native
    #active: composite
  application:
    name: config-server
  cloud.config.server.git.uri: file:///Users/h2user/microservices/microservice-workshop-kotlin/solution/config-server/src/main/resources/config-repo
  cloud:
    config:
      server:
        #native.search-locations: file:///Users/h2user/microservices/microservice-workshop-kotlin/solution/config-server/src/main/resources/config-repo
        #native.default-label: dev
      discovery.enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/
    registryFetchIntervalSeconds: 1
    register-with-eureka: true
  instance:
    leaseRenewalIntervalInSeconds: 1
