spring:
  application:
    name: movie-aggregator-service-rt
  redis:
    host: localhost
    port: 6379
#  session:
#    store-type: redis

info:
  app:
    name: Movie Aggregator Service (RT)

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,hystrix.stream

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/

# set the threshold low so we can see the circuit trip
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 3
server:
  port: 8084