server.port: 8089
spring:
  profiles.active: native
  application.name: config-server
  #cloud.config.server.git.uri: file:///Users/h2user/workspace/MovieProject/config-repository
  cloud.config.server.native.search-locations: file:///Users/h2user/workspace/MovieProject/config-repository
  cloud.config.server.native.default-label: test
  cloud.config.discovery.enabled: true

#  redis:
#    host: localhost
#    port: 6379
#  security:
#    user:
#      name: configUser
#      password: configPassword
#      roles: SYSTEM

eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/
    registryFetchIntervalSeconds: 1
    register-with-eureka: true
  instance:
    leaseRenewalIntervalInSeconds: 1
