spring:
  application:
    name: movie-award-service
  redis:
    host: localhost
    port: 6379

info:
  app:
    name: Movie Award Service

management:
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/

server:
  port: 8083
